
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-13T23:25:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "088cc782ebe38fcca0137a1b4f35ffaa205a9fd5",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
