shortcut_module_list:
- gtn_client
- factor_gtn
services:
  gtn_client:
    gtn:
      secret: ~
      url: https://open.hscloud.cn
      app_key: ~
  factor_gtn:
    gtn:
      secret: ~
      url: https://open.hscloud.cn
      app_key: ~
