[tool.poetry]
name = "ses_message_definitions"
version = "0.1.1"
description = "protobuf message defintions"
authors = ["Vinu ESB <vinu.vijayakumaran_nair@reutlingen-university.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
protobuf = "^3.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
