
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-18T18:43:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad78dbe4fa353c5bf951d5eb5ddfebc9674e6a72",
 "version": "1.1.1.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
