# Aiosqlembic configuration file
title = "aiosqlembic"
[migrations]
base_directory = '{{ base_directory }}'
[dsn]
scheme = 'postgresql'
user = 'user'
password = 'password'
host = 'localhost'
port = '5432'
db = 'postgres'