# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class TransactionStatus(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    transaction_status_code = ... # type: typing___Text
    validated = ... # type: builtin___bool
    last_ledger_sequence = ... # type: builtin___int

    def __init__(self,
        *,
        transaction_status_code : typing___Optional[typing___Text] = None,
        validated : typing___Optional[builtin___bool] = None,
        last_ledger_sequence : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> TransactionStatus: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> TransactionStatus: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"last_ledger_sequence",u"transaction_status_code",u"validated"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"last_ledger_sequence",b"last_ledger_sequence",u"transaction_status_code",b"transaction_status_code",u"validated",b"validated"]) -> None: ...
