site_name: confdaora
site_description: Application configuration using dataclasses and TypedDict

theme:
    name: 'material'
    palette:
      primary: 'green'
      accent: 'grey'
    logo: 'python-white.svg'
    favicon: 'favicon.png'

repo_name: dutradda/confdaora
repo_url: https://github.com/dutradda/confdaora
edit_uri: ''
google_analytics:
    - ''
    - 'auto'

nav:
    - confdaora: 'index.md'
    - Features: 'features.md'
    - Some Explanation: 'explain-concept.md'
    - Tutorial - User Guide:
        - Introduciton: 'tutorial/intro.md'
    - Benchmarks: 'benchmarks.md'
    - Help confdaora - Get Help: 'help.md'
    - Development - Contributing: 'contributing.md'
    - Changelog: changelog.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
