
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-10T12:22:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7faebe21758e526d4c98704b29b1227b7a49d06",
 "version": "2020.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
