apiVersion: v1
name: opsy
appVersion: 0.0.1
version: 0.0.1
description: It's Opsy! A simple multi-user/role operations inventory system with aspirations.
home: https://github.com/objectrocket/opsy
sources:
  - https://github.com/objectrocket/opsy
maintainers:
  - name: ObjectRocket SRE Team
    email: sre@objectrocket.com
