language: python
python: 3.8
dist: xenial
env:
  global:
    - DRF="djangorestframework==3.11.0"
    - DJANGO="django==3.0.2"
    - ITERTABLE="itertable==2.0.0"
matrix:
  include:
    - name: "Defaults (Python 3.8, Django 3.0, DRF 3.11, IterTable 2.0)"
    - name: "+ immediate"
      env:
        - NOTHREADING="1"
    - name: "+ celery"
      env:
        - CELERY="celery==4.4.0"
        - REDIS="redis"
    - name: "+ wq.db"
      env:
        - WQDB="wq.db==1.2.0"
    - name: "+ wq.db + reversion"
      env:
        - WQDB="wq.db==1.2.0"
        - REVERSION="django-reversion"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Django 2.2"
      env:
        - DJANGO="django==2.2.9"
    - name: "Django 1.11"
      env:
        - DJANGO="django==1.11.27"
    - name: "Python 3.5, Django 2.2"
      python: "3.5"
      env:
        - DJANGO="django==2.2.9"
    - name: "Python 3.4, Django 2.0, DRF 3.9"
      python: "3.4"
      env:
        - DJANGO="django==2.0.13"
        - DRF="djangorestframework==3.9.4"
    - name: "Python 2.7, Django 1.8, DRF 3.6 + celery"
      python: "2.7"
      env:
        - DJANGO="django==1.8.19"
        - DRF="djangorestframework==3.6.4"
        - CELERY="celery==4.2.1"
        - REDIS="redis"
    - name: "Code Lint"
      env:
        - LINT="flake8"
    - name: "JavaScript Build"
      language: node
      node_js: 12
      install:
        - npm ci
        - npm run bootstrap
      script:
        - npm run lint
        - npm test
        - npm run build
install:
 - pip install $DJANGO $CELERY $REDIS $DRF $ITERTABLE $WQDB $REVERSION $LINT
 - pip install natural-keys python-dateutil
script:
 - ./runtests.sh
services:
 - redis-server
