# Generated by Django 2.2.4 on 2019-08-22 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_office_senate_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='body',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 0, 0, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='aggregate_candidates',
            field=models.BooleanField(default=True, help_text="Determines whether to globally aggregate vote totals of this party's candidates during an election."),
        ),
    ]
