
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-13T14:06:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "917270a9b735a998d9d7db1016a98caeb3085e53",
 "version": "0.0.1.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
