---
language: python
services:
- docker

python:
- "3.6"

jobs:
  include:
  - stage: build
    before_install:
    - export IMAGE=robotpy/cscore-ci:latest
    - docker pull $IMAGE
    - docker run $IMAGE pip --version
    script:
    - python setup.py sdist
    - docker run --mount type=bind,source="$(pwd)"/dist,target=/dist $IMAGE /bin/sh -c "pip install -v /$(echo dist/*.tar.gz) && python3 -m cscore --help"

  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

  - stage: deploy
    if: tag IS present
    python: "3.6"
    install: skip
    script: skip
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist
      on:
        tags: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
