site_name: Keras batchflow
repo_url: https://github.com/maxsch3/keras-batchflow/
theme: readthedocs

extra_css:
    - css/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

plugins:
  - mkdocs-jupyter

nav:
  - Home: index.md
  - User guide: user_guide.md
  - Examples:
    - basic usage: titanic_example.ipynb
  - API: reference.md