[tool.poetry]
name = "ses_message_definitions"
version = "0.1.3"
description = "protobuf message defintions for ses "
authors = ["Vinu ESB <vinu.vijayakumaran_nair@reutlingen-university.de>"]

[tool.poetry.dependencies]
python = "^3.7"
protobuf = "^3.11.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
