[tool.poetry]
name = "trickt"
version = "0.1.1"
description = "Search data for trickiness and obfuscation."
authors = ["krayzpipes <kylepiper29@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/krayzpipes/trickt"
keywords = ["security", "obfuscate"]
classifiers = [
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Security",
]
packages = [
  { include= "trickt", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.2"
bandit = "^1.6.2"

[tool.poetry.scripts]
trickt = 'trickt:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
