[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyberny"
version = "0.6.0"
description = "Molecular/crystal structure optimizer"
readme = "README.md"
authors = ["Jan Hermann <dev@jan.hermann.name>"]
repository = "https://github.com/jhrmnn/pyberny"
documentation = "https://jhrmnn.github.io/pyberny"
license = "MPL-2.0"
packages = [
    { include = "berny", from = "src" },
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "^3.5"
numpy = "^1.15"
pytest = { version = "^3.6", optional = true }
coverage = { version = "^4.5", optional = true }
sphinx = { version = "^2.2", optional = true }
sphinxcontrib-katex = { version = "^0.5.1", optional = true }
importlib-metadata = { version = "^1.5.0", optional = true }

[tool.poetry.extras]
test = ["pytest", "coverage"]
doc = ["sphinx", "sphinxcontrib-katex", "importlib-metadata"]

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = ">=18.8"
flake8-comprehensions = ">=1.4"
flake8-quotes = "^2"
black = { version = ">=19-beta.0", python = "^3.6" }
pep8-naming = ">=0.7"
isort = "^4.3"
pydocstyle = "^5.0.1"

[tool.poetry.scripts]
berny = "berny.cli:main"

[tool.black]
target-version = ["py36"]
skip-string-normalization = true
