
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-09T11:28:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "655465cf744e9800b6b3e0aea0bd4d0981b9cb84",
 "version": "0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
