[tool.poetry]
name = "tasmidi"
version = "0.1.0"
description = ""
authors = ["Mark Rawls <markrawls96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
mido = "^1.2.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
tasmidi-map = 'tasmidi.map:main'
tasmidi-convert = 'tasmidi.convert:main'
