
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-10T17:42:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a74c09c49f2e14046acd4b0eeb861f8fef6bca96",
 "version": "0.1.alpha8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
