# Generated by Django 2.2.10 on 2020-02-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_filter_conditions', '0002_auto_20200218_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='named_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='flexible_filter_conditions.NamedCondition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='operation',
            field=models.CharField(choices=[('and', 'and'), ('or', 'or'), ('xor', 'xor (one or the other)')], max_length=30, verbose_name='Operation'),
        ),
    ]
