
__all__ = [
    'EVT_DRI_SHUTDOWN', 'EVT_DRI_SUBMIT', 'EVT_DRI_BEFORE',
    'EVT_DRI_AFTER', 'EVT_DRI_RETURN', 'EVT_DRI_OTHER',
    'EVT_DRI_SUSPEND', 'EVT_DRI_ERROR', 'EVT_DRI_CLEAN'
]

EVT_DRI_SHUTDOWN = '|EVT|SHUTDOWN|'
EVT_DRI_SUBMIT = '|EVT|SUBMIT|'

EVT_DRI_BEFORE = '|EVT|BEFORE|'
EVT_DRI_AFTER = '|EVT|AFTER|'
EVT_DRI_RETURN = '|EVT|RETURN|'

EVT_DRI_OTHER = '|EVT|OTHER|'

EVT_DRI_SUSPEND = '|EVT|SUSPEND|'

EVT_DRI_ERROR = '|EVT|ERROR|'

EVT_DRI_CLEAN = '|EVT|CLEAN|'
