# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mindbody_api.models.staff import Staff  # noqa: F401,E501


class ContactLogComment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'text': 'str',
        'created_date_time': 'datetime',
        'created_by': 'Staff'
    }

    attribute_map = {
        'id': 'Id',
        'text': 'Text',
        'created_date_time': 'CreatedDateTime',
        'created_by': 'CreatedBy'
    }

    def __init__(self, id=None, text=None, created_date_time=None, created_by=None):  # noqa: E501
        """ContactLogComment - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._text = None
        self._created_date_time = None
        self._created_by = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if text is not None:
            self.text = text
        if created_date_time is not None:
            self.created_date_time = created_date_time
        if created_by is not None:
            self.created_by = created_by

    @property
    def id(self):
        """Gets the id of this ContactLogComment.  # noqa: E501

        The comment’s ID.  # noqa: E501

        :return: The id of this ContactLogComment.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ContactLogComment.

        The comment’s ID.  # noqa: E501

        :param id: The id of this ContactLogComment.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def text(self):
        """Gets the text of this ContactLogComment.  # noqa: E501

        The comment’s body text.  # noqa: E501

        :return: The text of this ContactLogComment.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ContactLogComment.

        The comment’s body text.  # noqa: E501

        :param text: The text of this ContactLogComment.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def created_date_time(self):
        """Gets the created_date_time of this ContactLogComment.  # noqa: E501

        The local time when the comment was created.  # noqa: E501

        :return: The created_date_time of this ContactLogComment.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time):
        """Sets the created_date_time of this ContactLogComment.

        The local time when the comment was created.  # noqa: E501

        :param created_date_time: The created_date_time of this ContactLogComment.  # noqa: E501
        :type: datetime
        """

        self._created_date_time = created_date_time

    @property
    def created_by(self):
        """Gets the created_by of this ContactLogComment.  # noqa: E501

        Information about the staff member who created the comment.  # noqa: E501

        :return: The created_by of this ContactLogComment.  # noqa: E501
        :rtype: Staff
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ContactLogComment.

        Information about the staff member who created the comment.  # noqa: E501

        :param created_by: The created_by of this ContactLogComment.  # noqa: E501
        :type: Staff
        """

        self._created_by = created_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactLogComment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactLogComment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
