# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetBookableItemsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_type_ids': 'list[int]',
        'location_ids': 'list[int]',
        'staff_ids': 'list[int]',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'appointment_id': 'int',
        'ignore_default_session_length': 'bool',
        'limit': 'int',
        'offset': 'int'
    }

    attribute_map = {
        'session_type_ids': 'SessionTypeIds',
        'location_ids': 'LocationIds',
        'staff_ids': 'StaffIds',
        'start_date': 'StartDate',
        'end_date': 'EndDate',
        'appointment_id': 'AppointmentId',
        'ignore_default_session_length': 'IgnoreDefaultSessionLength',
        'limit': 'Limit',
        'offset': 'Offset'
    }

    def __init__(self, session_type_ids=None, location_ids=None, staff_ids=None, start_date=None, end_date=None, appointment_id=None, ignore_default_session_length=None, limit=None, offset=None):  # noqa: E501
        """GetBookableItemsRequest - a model defined in Swagger"""  # noqa: E501

        self._session_type_ids = None
        self._location_ids = None
        self._staff_ids = None
        self._start_date = None
        self._end_date = None
        self._appointment_id = None
        self._ignore_default_session_length = None
        self._limit = None
        self._offset = None
        self.discriminator = None

        self.session_type_ids = session_type_ids
        if location_ids is not None:
            self.location_ids = location_ids
        if staff_ids is not None:
            self.staff_ids = staff_ids
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if appointment_id is not None:
            self.appointment_id = appointment_id
        if ignore_default_session_length is not None:
            self.ignore_default_session_length = ignore_default_session_length
        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset

    @property
    def session_type_ids(self):
        """Gets the session_type_ids of this GetBookableItemsRequest.  # noqa: E501

        A list of the requested session type IDs.  # noqa: E501

        :return: The session_type_ids of this GetBookableItemsRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._session_type_ids

    @session_type_ids.setter
    def session_type_ids(self, session_type_ids):
        """Sets the session_type_ids of this GetBookableItemsRequest.

        A list of the requested session type IDs.  # noqa: E501

        :param session_type_ids: The session_type_ids of this GetBookableItemsRequest.  # noqa: E501
        :type: list[int]
        """
        if session_type_ids is None:
            raise ValueError("Invalid value for `session_type_ids`, must not be `None`")  # noqa: E501

        self._session_type_ids = session_type_ids

    @property
    def location_ids(self):
        """Gets the location_ids of this GetBookableItemsRequest.  # noqa: E501

        A list of the requested location IDs.  # noqa: E501

        :return: The location_ids of this GetBookableItemsRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._location_ids

    @location_ids.setter
    def location_ids(self, location_ids):
        """Sets the location_ids of this GetBookableItemsRequest.

        A list of the requested location IDs.  # noqa: E501

        :param location_ids: The location_ids of this GetBookableItemsRequest.  # noqa: E501
        :type: list[int]
        """

        self._location_ids = location_ids

    @property
    def staff_ids(self):
        """Gets the staff_ids of this GetBookableItemsRequest.  # noqa: E501

        A list of the requested staff IDs.  # noqa: E501

        :return: The staff_ids of this GetBookableItemsRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._staff_ids

    @staff_ids.setter
    def staff_ids(self, staff_ids):
        """Sets the staff_ids of this GetBookableItemsRequest.

        A list of the requested staff IDs.  # noqa: E501

        :param staff_ids: The staff_ids of this GetBookableItemsRequest.  # noqa: E501
        :type: list[int]
        """

        self._staff_ids = staff_ids

    @property
    def start_date(self):
        """Gets the start_date of this GetBookableItemsRequest.  # noqa: E501

        The start date of the requested date range.   <br />Default: **today’s date**  # noqa: E501

        :return: The start_date of this GetBookableItemsRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this GetBookableItemsRequest.

        The start date of the requested date range.   <br />Default: **today’s date**  # noqa: E501

        :param start_date: The start_date of this GetBookableItemsRequest.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this GetBookableItemsRequest.  # noqa: E501

        The end date of the requested date range.   <br />Default: **StartDate**  # noqa: E501

        :return: The end_date of this GetBookableItemsRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this GetBookableItemsRequest.

        The end date of the requested date range.   <br />Default: **StartDate**  # noqa: E501

        :param end_date: The end_date of this GetBookableItemsRequest.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def appointment_id(self):
        """Gets the appointment_id of this GetBookableItemsRequest.  # noqa: E501

        If provided, filters out the appointment with this ID.  # noqa: E501

        :return: The appointment_id of this GetBookableItemsRequest.  # noqa: E501
        :rtype: int
        """
        return self._appointment_id

    @appointment_id.setter
    def appointment_id(self, appointment_id):
        """Sets the appointment_id of this GetBookableItemsRequest.

        If provided, filters out the appointment with this ID.  # noqa: E501

        :param appointment_id: The appointment_id of this GetBookableItemsRequest.  # noqa: E501
        :type: int
        """

        self._appointment_id = appointment_id

    @property
    def ignore_default_session_length(self):
        """Gets the ignore_default_session_length of this GetBookableItemsRequest.  # noqa: E501

        When `true`, availabilities that are non-default return, for example, a 30-minute availability with a 60-minute default session length.<br />  When `false`, only availabilities that have the default session length return.  # noqa: E501

        :return: The ignore_default_session_length of this GetBookableItemsRequest.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_default_session_length

    @ignore_default_session_length.setter
    def ignore_default_session_length(self, ignore_default_session_length):
        """Sets the ignore_default_session_length of this GetBookableItemsRequest.

        When `true`, availabilities that are non-default return, for example, a 30-minute availability with a 60-minute default session length.<br />  When `false`, only availabilities that have the default session length return.  # noqa: E501

        :param ignore_default_session_length: The ignore_default_session_length of this GetBookableItemsRequest.  # noqa: E501
        :type: bool
        """

        self._ignore_default_session_length = ignore_default_session_length

    @property
    def limit(self):
        """Gets the limit of this GetBookableItemsRequest.  # noqa: E501

        Number of results to include, defaults to 100  # noqa: E501

        :return: The limit of this GetBookableItemsRequest.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetBookableItemsRequest.

        Number of results to include, defaults to 100  # noqa: E501

        :param limit: The limit of this GetBookableItemsRequest.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this GetBookableItemsRequest.  # noqa: E501

        Page offset, defaults to 0.  # noqa: E501

        :return: The offset of this GetBookableItemsRequest.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this GetBookableItemsRequest.

        Page offset, defaults to 0.  # noqa: E501

        :param offset: The offset of this GetBookableItemsRequest.  # noqa: E501
        :type: int
        """

        self._offset = offset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetBookableItemsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetBookableItemsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
