# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mindbody_api.models.client_service import ClientService  # noqa: F401,E501


class UpdateClientServiceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_service': 'ClientService'
    }

    attribute_map = {
        'client_service': 'ClientService'
    }

    def __init__(self, client_service=None):  # noqa: E501
        """UpdateClientServiceResponse - a model defined in Swagger"""  # noqa: E501

        self._client_service = None
        self.discriminator = None

        if client_service is not None:
            self.client_service = client_service

    @property
    def client_service(self):
        """Gets the client_service of this UpdateClientServiceResponse.  # noqa: E501

        Contains information about the updated service.  # noqa: E501

        :return: The client_service of this UpdateClientServiceResponse.  # noqa: E501
        :rtype: ClientService
        """
        return self._client_service

    @client_service.setter
    def client_service(self, client_service):
        """Sets the client_service of this UpdateClientServiceResponse.

        Contains information about the updated service.  # noqa: E501

        :param client_service: The client_service of this UpdateClientServiceResponse.  # noqa: E501
        :type: ClientService
        """

        self._client_service = client_service

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateClientServiceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateClientServiceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
