[tool.poetry]
name = "rtpi"
version = "0.1.3"
description = ""
authors = ["Marco Rougeth <marco@rougeth.com>"]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.11.1"

[tool.poetry.dev-dependencies]
ipython = "^7.12.0"
ipdb = "^0.12.3"
pytest = "^5.3.5"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
