version: "3.7"

services:
  metadata_store:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebonite

  artifact_store:
    image: scality/s3server:mem-latest
    ports:
      - 8008:8000
