[tool.poetry]
name = "ttmr"
version = "0.5.0-alpha"
description = ""
authors = ["Mark Gemmill <gitlab@markgemmill.com>"]

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4.3"
arrow = "^0.15.5"
colorama = "^0.4.3"
docopt-ng = "^0.7.2"
prompt-toolkit = "^3.0.3"
python-dateutil = "^2.8.1"
tabulate = "^0.8.6"
tomlkit = "^0.5.8"
sqlalchemy = "^1.3.13"
pendulum = "^2.0.5"

[tool.poetry.dev-dependencies]

[tool.dover]
versioned_files = [
    "src/ttmr/cli.py",
    "pyproject.toml"
]

[tool.poetry.scripts]
ttmr = 'ttmr.cli:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

