[tool.poetry]
name = "test-pypi-poetry"
version = "0.1.1"
description = "Testing PyPi & Poetry"
authors = ["Christopher Farrenden <cfarrend@gmail.com>"]

readme = "README.md"

packages = [
    { include = "test-pypi-poetry" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
