
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-09T18:51:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6971ef5676110a19948fbdbee0b2d07ee65d719",
 "version": "1.0.0.post.dev95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
