
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-02-14T08:54:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "93fd92a2bc26e12b78bb805ff2e916603c9c4229",
 "version": "1.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
