[tool.poetry]
name = "djangovue"
version = "0.0.12"
description = "A set of helper tags and form widgets for making django and vue play nicely."
authors = ["Bradley Stuart Kirton <bradleykirton@gmail.com>"]
license = "MIT"
repository = "https://gitlab.com/BradleyKirton/djangovue/"
homepage = "https://gitlab.com/BradleyKirton/djangovue/"
readme = "README.md"
keywords=[
	"django",
	"vue",
]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.1",
]
include = [
	"djangovue/static/djangovue/djangovue.js*"
]
exclude = [
	"djangovue/examples/**",
	"djangovue/tests/**",
	"djangovue/plugins/**"
]

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.1"

[tool.poetry.dev-dependencies]
django = "^2.1"
django-crispy-forms = "^1.7"
Pygments = "^2.3"
pytest = "^4.3"
pytest-cov = "^2.6"
pytest-sugar = "^0.9.2"
django-coverage-plugin = "^1.6"
pytest-django = "^3.4"
bumpversion = "^0.5.3"
twine = "^1.13"
black = "18.9b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
