
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-13T13:00:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "36d44b735c242fe9e54c4231b980fce02b11dd81",
 "version": "1.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
