from __future__ import absolute_import
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beam_interactive_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import beam_runner_api_pb2 as beam__runner__api__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='beam_interactive_api.proto',
  package='org.apache.beam.model.interactive.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x62\x65\x61m_interactive_api.proto\x12$org.apache.beam.model.interactive.v1\x1a\x15\x62\x65\x61m_runner_api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x14TestStreamFileHeader\x12\x0b\n\x03tag\x18\x01 \x01(\t\"\xea\x01\n\x14TestStreamFileRecord\x12Z\n\x07\x65lement\x18\x01 \x01(\x0b\x32G.org.apache.beam.model.pipeline.v1.TestStreamPayload.TimestampedElementH\x00\x12/\n\twatermark\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x33\n\x0fprocessing_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x10\n\x0erecorded_eventBF\n$org.apache.beam.model.interactive.v1B\x0eInteractiveApiZ\x0einteractive_v1b\x06proto3')
  ,
  dependencies=[beam__runner__api__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TESTSTREAMFILEHEADER = _descriptor.Descriptor(
  name='TestStreamFileHeader',
  full_name='org.apache.beam.model.interactive.v1.TestStreamFileHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='org.apache.beam.model.interactive.v1.TestStreamFileHeader.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=159,
)


_TESTSTREAMFILERECORD = _descriptor.Descriptor(
  name='TestStreamFileRecord',
  full_name='org.apache.beam.model.interactive.v1.TestStreamFileRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='org.apache.beam.model.interactive.v1.TestStreamFileRecord.element', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='watermark', full_name='org.apache.beam.model.interactive.v1.TestStreamFileRecord.watermark', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processing_time', full_name='org.apache.beam.model.interactive.v1.TestStreamFileRecord.processing_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='recorded_event', full_name='org.apache.beam.model.interactive.v1.TestStreamFileRecord.recorded_event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=162,
  serialized_end=396,
)

_TESTSTREAMFILERECORD.fields_by_name['element'].message_type = beam__runner__api__pb2._TESTSTREAMPAYLOAD_TIMESTAMPEDELEMENT
_TESTSTREAMFILERECORD.fields_by_name['watermark'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TESTSTREAMFILERECORD.fields_by_name['processing_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TESTSTREAMFILERECORD.oneofs_by_name['recorded_event'].fields.append(
  _TESTSTREAMFILERECORD.fields_by_name['element'])
_TESTSTREAMFILERECORD.fields_by_name['element'].containing_oneof = _TESTSTREAMFILERECORD.oneofs_by_name['recorded_event']
_TESTSTREAMFILERECORD.oneofs_by_name['recorded_event'].fields.append(
  _TESTSTREAMFILERECORD.fields_by_name['watermark'])
_TESTSTREAMFILERECORD.fields_by_name['watermark'].containing_oneof = _TESTSTREAMFILERECORD.oneofs_by_name['recorded_event']
DESCRIPTOR.message_types_by_name['TestStreamFileHeader'] = _TESTSTREAMFILEHEADER
DESCRIPTOR.message_types_by_name['TestStreamFileRecord'] = _TESTSTREAMFILERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestStreamFileHeader = _reflection.GeneratedProtocolMessageType('TestStreamFileHeader', (_message.Message,), dict(
  DESCRIPTOR = _TESTSTREAMFILEHEADER,
  __module__ = 'beam_interactive_api_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.model.interactive.v1.TestStreamFileHeader)
  ))
_sym_db.RegisterMessage(TestStreamFileHeader)

TestStreamFileRecord = _reflection.GeneratedProtocolMessageType('TestStreamFileRecord', (_message.Message,), dict(
  DESCRIPTOR = _TESTSTREAMFILERECORD,
  __module__ = 'beam_interactive_api_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.model.interactive.v1.TestStreamFileRecord)
  ))
_sym_db.RegisterMessage(TestStreamFileRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$org.apache.beam.model.interactive.v1B\016InteractiveApiZ\016interactive_v1'))
# @@protoc_insertion_point(module_scope)
