# Generated by Django 2.0.1 on 2018-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("entity", "0002_auto_20180117_2043")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
