[tool.poetry]
name = "hadrosaur"
version = "0.3.2"
description = "[WIP] Manage a large amount of computed resources, such as files, imports, etc."
authors = ["Jay R Bolton <jayrbolton@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/jayrbolton/hadrosaur"
documentation = "https://github.com/jayrbolton/hadrosaur"
repository = "https://github.com/jayrbolton/hadrosaur"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "5.3.5"
