[tool.poetry]
name = "transmission-clutch"
version = "2.0.dev0"
description = "An RPC client library for the Transmission bittorrent client"
authors = ["mhadam <michael@hadam.us>"]
license = "MIT"
packages = [
    { include = "clutch" }
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
mypy = "^0.761"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
