
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-18T12:34:13+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "c5a37a5223ed13653ab4d36abb0726c84617af43",
 "version": "0.1.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
