[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "delver"
dist-name = "pydelver"
author = "Alex Sippel"
author-email = "asippel@narrativescience.com"
home-page = "https://github.com/NarrativeScience/delver"
license = "BSD-3-Clause"
description-file = "README.md"
requires = [
    "colorful>=0.4.0", "six>=1.10.0", "terminaltables>=3.1.0"
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 2",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.6,<4"
keywords = "data,command line tools,json"

[tool.flit.sdist]
include = ["LICENSE.md"]
exclude = ["tests/"]

[tool.flit.scripts]
delve = "delver.delve:main"