
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-14T18:00:58-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e676504bd09177d9162e586613e1b5a222de9a5d",
 "version": "0.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
