# Filename for the patch to apply on top of a snapshot,
# if the project is using git.
COMMIT_PATCH_BASENAME = 'anyscale-patch'

ENDPOINTS = {
    "project_create": "/project/create",
    "project_list": "/project/list",
    "project_sessions": "/project/sessions",
    "session_autosync_add_device": "/session/autosync_add_device",
    "session_autosync_started": "/session/autosync_started",
    "session_commands": "/session/commands",
    "session_create": "/session/create",
    "session_describe": "/session/describe",
    "session_execute": "/session/execute",
    "session_execution_logs": "/session/execution_logs",
    "session_finish_command": "/session/finish_command",
    "session_kill_command": "/session/kill_command",
    "session_list": "/session/list",
    "session_overview": "/session/overview",
    "session_report_command": "/session/report_command",
    "session_startup_log": "/session/startup_log",
    "session_stop": "/session/stop",
    "session_sync": "/session/sync",
    "session_upload_command_logs": "/session/upload_command_logs",
    "snapshot_archive": "/snapshot/archive",
    "snapshot_create": "/snapshot/create",
    "snapshot_delete": "/snapshot/delete",
    "snapshot_describe": "/snapshot/describe",
    "snapshot_get": "/snapshot/get",
    "snapshot_list": "/snapshot/list",
    "user_info": "/user/info",
    "user_login": "/user/login",
    "user_register": "/user/register",
    "user_server_session_token": "/user/server_session_token",
}
