[tool.poetry]
name = "botwriter"
version = "0.1.2"
description = ""
authors = ["Mattis Abrahamsson <mattis.abrahamsson@gmail.com>"]

[tool.poetry.scripts]
start = "botwriter:main"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.22.0"
pandas = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
