[tool.poetry]
name = "ak-django-activity-stream"
version = "0.8.0.post1"
description = "Generate generic activity streams from the actions on your site. Users can follow any actors\\' activities for personalized streams."
authors = ["Appknox <engineering@appknox.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/appknox/django-activity-stream"
readme = "README.rst"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Topic :: Utilities'
]
packages=[
    { include = "actstream/**/*.py" },
]

include = [
    "actstream/locale/*/LC_MESSAGES/*.po",
    "actstream/templates/actstream/*.html"
]

[tool.poetry.dependencies]
python = "^3.6"
django-jsonfield = {version = ">=1.0.1", optional = true}
django-jsonfield-compat = {version = ">=0.4.4", optional = true}

[tool.poetry.extras]
jsonfield = ["django-jsonfield", "django-jsonfield-compat"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
