[tool.poetry]
name = "clean_auckland_gtfs"
version = "0.4.3"
description = "Python 3.6+ code for cleaning Auckland, New Zealand GTFS feeds"
authors = ["Alex Raichev <araichev@mrcagney.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6|^3.7"
gtfs_kit = "<4"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
