# We define two secrets, one that's used for the db migration job, and one that
# is for the release. We do this because the database migration job needs
# config too but we don't want to have orphaned resources if we helm delete.
{{- define "secret.content" -}}
data:
  OPSY_ADMIN_PASSWORD: {{ required "A valid opsy.admin_password entry required!" .Values.opsy.admin_password | b64enc | quote }}
  OPSY_SECRET_KEY: {{ required "A valid opsy.app.secret_key entry required!" .Values.opsy.app.secret_key | b64enc | quote }}
  OPSY_DATABASE_URI: {{ required "A valid opsy.app.database_uri entry required!" .Values.opsy.app.database_uri | b64enc | quote }}
  OPSY_LDAP_BIND_USER_PASSWORD: {{ .Values.opsy.auth.ldap_bind_user_password | b64enc | quote }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsy.fullname" . }}-database-migrations
  labels:
{{ include "opsy.migrationLabels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{ include "secret.content" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsy.fullname" . }}
  labels:
{{ include "opsy.labels" . | indent 4 }}
{{ include "secret.content" . }}
