---
- name: Debug for ask_sudo_pass
  debug:
    msg: "{{ setup_providers }}"

- name: Install dependencies per provider
  include_tasks: "{{ indv_prov }}_deps.yml"
  with_items: "{{ setup_providers }}"
  loop_control:
    loop_var: indv_prov

- name: Install os-specific dependencies CentOS/RHEL
- name: "Install os-specific dependencies Fedora"
  include_tasks: "setup_dnf_deps.yml"
  when: setup_providers | length == 0  and ansible_distribution == 'Fedora'

- name: "Install os-specific dependencies CentOS/RHEL"
  include_tasks: "setup_yum_deps.yml"
  when: setup_providers | length == 0  and (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS')

- name: Install all dependencies
  include_tasks: "{{ setup_prov }}_deps.yml"
  with_items:
    - beaker
    - libvirt
    - docs
    - test
    - setup_selinux
    - docker
  when: setup_providers | length == 0
  loop_control:
    loop_var: setup_prov
