[tool.towncrier]
package = "convtools"
package_dir = "src"
filename = "CHANGELOG.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.rst"
issue_format = "`#{issue} <https://github.com/itechart-almakov/convtools/issues/{issue}>`_"
