# Generated by Django 2.2.3 on 2019-07-09 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_auto_20190709_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organizationclassification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationclassification',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
