# Generated by Django 2.2.3 on 2019-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_auto_20190709_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
