# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 88
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.eggs
  | \.vscode
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''


# Poetry package information below.

[tool.poetry]
name = "networkparse"
version = "1.7.7"
description = "Simple read-only parser for Cisco IOS, NX-OS, HP, and other network device running configs"
readme = "README.rst"
authors = ["Ryan Morehart <ryan@xylok.io>"]
homepage = "https://gitlab.com/xylok/networkparse"
documentation = "https://networkparse.readthedocs.io/en/latest/"
license = "MIT"
keywords = ["xylok", "cyber"]
classifiers=[
   "Development Status :: 4 - Beta",
   "Environment :: Console",
   "Intended Audience :: Developers",
   "Operating System :: OS Independent",
   "Topic :: Software Development :: Libraries :: Python Modules",
   "Topic :: Software Development :: Quality Assurance",
  #  "Programming Language :: Python :: 3",
   # "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = "^0.6.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allow-prereleases = true}
poetry = "*"
sphinx = "*"
sphinx-autobuild = "*"
sphinx-rtd-theme = "*"
pytest = "^3.6"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
