
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-10T02:03:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf0cd51f14b09cb8cf72ccf124011d40f395bcf7",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
