[tool.poetry]
name = "aerie"
version = "0.0.1b0"
description = "A database library for asyncio."
authors = ["alex.oleshkevich <alex.oleshkevich@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
databases = "^0.2.5"
asyncpg = "^0.18.3"
psycopg2-binary = "^2.8.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
aiosqlite = "^0.10.0"
pytest-asyncio = "^0.10.0"
coverage = "^4.5"
pytest-cov = "^2.8.1"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
