# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"normalize_nifti": "00_nifti_utils.ipynb"}

modules = ["nifti_utils.py"]

doc_url = "https://pfdamasceno.github.io/gema_utils/"

git_url = "https://github.com/pfdamasceno/gema_utils/tree/master/"

def custom_doc_links(name): return None
