HistoricalWeatherTW:
  STATION_CSV: 'config/CSV/station_test.csv'
  OUTPUT_PATH: 'temp/year_result.csv'
  BEGIN_DATE: 2019-10-1
  END_DATE: 2019-10-2
  QUERY_FORMAT: QueryFormat.DAY  # MONTH, YEAR
  CONVERT2NUM: 'True'  # convert to number or not
