[tool.poetry]
name = "chatserver"
version = "0.1.4"
description = "A chatserver written in python"
authors = ["Luke Spademan <info@lukespademan.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/mokytis/python-chatserver"

[tool.poetry.dependencies]
python = "^3.8.0"
sqlalchemy = "^1.3.13"
werkzeug = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^19.10b0", allow-prereleases = true}
pylint = "^2.4.4"

[tool.poetry.scripts]
run = "chatserver:chatserver.main"
chatserver = "chatserver:chatserver.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
