
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-07T14:25:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ee6b30ee4d05431d2adfbadab731d58e1408cee",
 "version": "0.0.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
