
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-20T13:39:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "372c88530e97d08ff37f6d8959a0d0b2a3f0d820",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
