[tool.poetry]
name = "ses_device_driver"
version = "0.2.2"
description = "Device drivers/helper classes for each device in the ses of Werk150"
authors = ["Vinu ESB <vinu.vijayakumaran_nair@reutlingen-university.de>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
