arangodb:
  DB_end_point: createDB
  DB_service_host: arangoml.arangodb.cloud
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: https
  dbName: MLcas43wgargi31zns6axs8y
  password: ML2j0ryzepdheciyzyqpxt5f
  username: ML2dsd29dtdi7lzdhal6kodb
mlgraph:
  graphname: enterprise_ml_graph
