map_data = {
    "hotelChain": {
        "enumerationValues": [
            {
                "value": "quality inn"
            },
            {
                "value": "hyatt"
            },
            {
                "value": "Hyatt Renaissance"
            },
            {
                "value": "marriott"
            },
            {
                "value": "holiday inn"
            },
            {
                "value": "hilton"
            },
            {
                "value": "motel 6"
            }
        ],
        "valueSelectionStrategy": "ORIGINAL_VALUE"
    },
    "negativeExpression": {
        "enumerationValues": [
            {
                "value": "no",
                "synonyms": [
                    "not",
                    "don't",
                    "dont"
                ]
            }
        ],
        "valueSelectionStrategy": "TOP_RESOLUTION"
    },
    "Product": {
        "enumerationValues": [
            {
                "value": "DESTINATION_SERVICES",
                "synonyms": [
                    "activities",
                    "activity"
                ]
            },
            {
                "value": "LODGING",
                "synonyms": [
                    "hotel rooms",
                    "hotel room",
                    "rental room",
                    "hotels",
                    "lodging",
                    "inn",
                    "rooms",
                    "resort",
                    "room",
                    "hotel"
                ]
            },
            {
                "value": "FLIGHT",
                "synonyms": [
                    "flight",
                    "flights",
                    "air"
                ]
            },
            {
                "value": "CAR",
                "synonyms": [
                    "rental",
                    "car rental",
                    "car"
                ]
            },
            {
                "value": "CRUISE",
                "synonyms": [
                    "crew ship",
                    "crewship",
                    "cruise"
                ]
            },
            {
                "value": "TRAIN",
                "synonyms": [
                    "railway"
                ]
            }
        ],
        "valueSelectionStrategy": "TOP_RESOLUTION"
    },
    "LodgingAmenities": {
        "enumerationValues": [
            {
                "value": "AIRPORT_SHUTTLE",
                "synonyms": [
                    "pick up from airport",
                    "picked up at airport",
                    "pick up at airport",
                    "pickup from airport",
                    "pick-up from airport",
                    "pickup at airport",
                    "pick-up at airport",
                    "pick up me",
                    "pick up us",
                    "picked us up",
                    "pick it up",
                    "pick us up",
                    "pick me up",
                    "picked me up",
                    "pick up service",
                    "drop us off",
                    "transfer from airport",
                    "airport pick up",
                    "shuttle pick up",
                    "airport pickup",
                    "airport pick-up",
                    "airport drop-off",
                    "airport transportation",
                    "airport transport",
                    "airport transfers",
                    "airport transfer",
                    "airport shuttle",
                    "shuttle service",
                    "shuttle bus",
                    "shuttle ride",
                    "car transfer",
                    "car service",
                    "car pickup",
                    "super shuttle",
                    "return transfer",
                    "shuttlepick up",
                    "picked up",
                    "pick up",
                    "pike up",
                    "collecting",
                    "pickup",
                    "minibus",
                    "speedishuttle",
                    "driver",
                    "airport",
                    "vehicle",
                    "taxi",
                    "taxis",
                    "cab",
                    "bus",
                    "car",
                    "ride",
                    "pick",
                    "picked",
                    "transportation",
                    "transport",
                    "transfers",
                    "transfer",
                    "teansfer",
                    "shuttled",
                    "shuttles",
                    "shuttle"
                ]
            },
            {
                "value": "BREAKFAST",
                "synonyms": [
                    "continental breakfast",
                    "free breakfast",
                    "breakfast buffet",
                    "complimentary breakfast",
                    "buffet breakfast",
                    "break fast",
                    "buffet",
                    "breakfasts",
                    "breakfast",
                    "breaskfast",
                    "brekfast",
                    "breskfast",
                    "breaksat",
                    "breakst",
                    "breakfest",
                    "meal",
                    "meals",
                    "food"
                ]
            },
            {
                "value": "CHECK_IN_CHECK_OUT",
                "synonyms": [
                    "check in early",
                    "check out late",
                    "check in sooner",
                    "late checking in",
                    "check in late",
                    "check out early",
                    "earlier check in",
                    "later check out",
                    "check in earlier",
                    "check out later",
                    "late check out",
                    "early check in",
                    "chexk in",
                    "check in",
                    "check out",
                    "checking out",
                    "checking in",
                    "late arrival",
                    "early arrival",
                    "check-in early",
                    "check inn",
                    "in late",
                    "late checkout",
                    "early check-in",
                    "early checkout",
                    "late checkin",
                    "checking late",
                    "check into",
                    "ck in",
                    "late check-out",
                    "early check",
                    "late check",
                    "checked in",
                    "checked out",
                    "check ins",
                    "arrive",
                    "recheck",
                    "checknin",
                    "checked",
                    "checking",
                    "checkout",
                    "checkin",
                    "check-in",
                    "check-out"
                ]
            },
            {
                "value": "BEDDING",
                "synonyms": [
                    "double or twin beds",
                    "2 double beds",
                    "king size bed",
                    "king size beds",
                    "king sized bed",
                    "king sized beds",
                    "queen size bed",
                    "queen size beds",
                    "queen sized bed",
                    "queen sized beds",
                    "full size bed",
                    "full size beds",
                    "full sized bed",
                    "full sized beds",
                    "twin size bed",
                    "twin size beds",
                    "twin sized bed",
                    "twin sized beds",
                    "double sofa bed",
                    "type of bed",
                    "pack and plays",
                    "pack and play",
                    "pack & play",
                    "roll away bed",
                    "roll away beds",
                    "crib/infant bed",
                    "infant bed",
                    "sofa bed",
                    "queen bed",
                    "queen beds",
                    "queen bedroom",
                    "double queen",
                    "double room",
                    "bed type",
                    "king size",
                    "king suite",
                    "king room",
                    "king rooms",
                    "king bed",
                    "king beds",
                    "single bed",
                    "single beds",
                    "double bed",
                    "double beds",
                    "twin bed",
                    "twin beds",
                    "twin bunk",
                    "twin bunks",
                    "two beds",
                    "portable crib",
                    "baby crib",
                    "rollaway bed",
                    "rollaway beds",
                    "roll-away bed",
                    "roll-away beds",
                    "handicap room",
                    "sleeper sofa",
                    "sheets",
                    "rollaway",
                    "sofabed",
                    "king",
                    "queen",
                    "bedroom",
                    "bedrooms",
                    "playpens",
                    "doubles",
                    "cots",
                    "cot",
                    "cribs",
                    "crib",
                    "bedding",
                    "beds",
                    "bed"
                ]
            },
            {
                "value": "PET_POLICY",
                "synonyms": [
                    "therapeutic chicken",
                    "pet friendly",
                    "dog friendly",
                    "cat friendly",
                    "pets policy",
                    "pet policy",
                    "dog rooms",
                    "animal",
                    "animals",
                    "chicken",
                    "dogs",
                    "dog",
                    "doggy",
                    "pet",
                    "puppy",
                    "puppys",
                    "puppies",
                    "cat",
                    "cats",
                    "kitten",
                    "kittens",
                    "pets"
                ]
            },
            {
                "value": "ROOM_AMENITY",
                "synonyms": [
                    "view of the ocean",
                    "view of the city",
                    "faces the ocean",
                    "faces the beach",
                    "ocean front view",
                    "swimming pool view",
                    "view of ocean",
                    "view of downtown",
                    "view of city",
                    "rooms that connect",
                    "room that connects",
                    "rooms that interconnect",
                    "room that interconnects",
                    "ocean view",
                    "mountain view",
                    "garden view",
                    "lake view",
                    "street view",
                    "beach view",
                    "beach side",
                    "beach front",
                    "ocean front",
                    "lake facing",
                    "river view",
                    "sea view",
                    "nice view",
                    "view balcony",
                    "view terrace",
                    "city view",
                    "skyline view",
                    "good view",
                    "air conditioner",
                    "air conditioning",
                    "adjoining room",
                    "adjoining rooms",
                    "connecting room",
                    "connecting rooms",
                    "interconnecting room",
                    "interconnecting rooms",
                    "dvd player",
                    "cable tv",
                    "cable t.v.",
                    "cable television",
                    "tv",
                    "t.v.",
                    "television",
                    "cable",
                    "movies",
                    "movie",
                    "ac",
                    "a.c.",
                    "air-con",
                    "air-conditioner",
                    "air-conditioning",
                    "seaview",
                    "oceanview",
                    "ocean",
                    "balcony",
                    "beach-front",
                    "beach",
                    "views",
                    "view"
                ]
            },
            {
                "value": "BATHROOM_FEATURES",
                "synonyms": [
                    "tub and shower",
                    "shared bathroom",
                    "bathroom towels",
                    "whirlpool room",
                    "blow dryer",
                    "blow dryers",
                    "hair dryers",
                    "hair dryer",
                    "hair dryers",
                    "jetted tubs",
                    "jetted tub",
                    "jet tub",
                    "bath tub",
                    "jacuzzi tub",
                    "hot water",
                    "walk-in shower",
                    "bath towels",
                    "beach towels",
                    "shower/tub",
                    "whirlpool",
                    "bathtub",
                    "tub",
                    "hairdryer",
                    "towels",
                    "shower",
                    "showers",
                    "bathrooms",
                    "hairdryers",
                    "bathroom"
                ]
            },
            {
                "value": "POOL",
                "synonyms": [
                    "interior swimming pool heated",
                    "indoor swimming pool",
                    "outdoor swimming pool",
                    "infinity pool",
                    "spa pool",
                    "indoor pool",
                    "outdoor pool",
                    "kids pool",
                    "heated pool",
                    "outside pool",
                    "hot tub",
                    "pool heated",
                    "rooftop pool",
                    "swimming pool",
                    "nearby pool",
                    "pool hours",
                    "jacuzzi",
                    "jucuzzi",
                    "hottub",
                    "pools",
                    "spa",
                    "pool"
                ]
            },
            {
                "value": "LUGGAGE",
                "synonyms": [
                    "this space intentionally left blank"
                ]
            },
            {
                "value": "CONTACT",
                "synonyms": [
                    "this space intentionally left blank"
                ]
            },
            {
                "value": "GYM",
                "synonyms": [
                    "this space intentionally left blank"
                ]
            },
            {
                "value": "KITCHENETTE",
                "synonyms": [
                    "fridge and microwave",
                    "mini fridge",
                    "small fridge",
                    "small microwave",
                    "small refridgerator",
                    "full kitchen",
                    "frying pan",
                    "frying pans",
                    "dish washer",
                    "coffee maker",
                    "coffee machine",
                    "coffee pot",
                    "coffee",
                    "pots",
                    "pans",
                    "dishes",
                    "dishwasher",
                    "refrigerator",
                    "fridge/freezer",
                    "freezer",
                    "microwave",
                    "microwaves",
                    "bbq",
                    "oven",
                    "stove",
                    "stovetop",
                    "mini-fridge",
                    "fridge",
                    "kitchen",
                    "kitchenette"
                ]
            },
            {
                "value": "PARKING",
                "synonyms": [
                    "on site parking",
                    "private parking space",
                    "free self parking",
                    "over night parking",
                    "free parking",
                    "R.V. parking",
                    "covered parking",
                    "parking garage",
                    "parking place",
                    "self parking",
                    "self park",
                    "valet parking",
                    "guest parking",
                    "parking pass",
                    "overnight parking",
                    "disabled parking",
                    "handicap parking",
                    "handicapped parking",
                    "truck parking",
                    "economical parking",
                    "trailer parking",
                    "onsite parking",
                    "on-site parking",
                    "secure parking",
                    "parking space",
                    "designated parking",
                    "auto parking",
                    "extended parking",
                    "leave car",
                    "parked",
                    "valet",
                    "park",
                    "parking"
                ]
            },
            {
                "value": "WIFI",
                "synonyms": [
                    "internet signal",
                    "internet service",
                    "internet cafe",
                    "internet",
                    "wi-fi",
                    "wireless",
                    "wifi"
                ]
            },
            {
                "value": "RESTAURANT_IN_HOTEL",
                "synonyms": [
                    "dining option",
                    "dining options",
                    "rooftop restaurant",
                    "free dinner",
                    "free lunch",
                    "bistro",
                    "bar",
                    "lounge",
                    "bar/lounge",
                    "restaurants",
                    "dine",
                    "dining",
                    "lunch",
                    "dinner",
                    "restaurant"
                ]
            },
            {
                "value": "ROOM_TYPE",
                "synonyms": [
                    "no smoking room",
                    "non smoking room",
                    "smoke free room",
                    "terrace apartment",
                    "executive room",
                    "president suite",
                    "presidential suite",
                    "smoke-free room",
                    "smoking rooms",
                    "smoking room",
                    "smoker room",
                    "non smoking",
                    "no smoking",
                    "nonsmoking room",
                    "non-smoking room",
                    "nonsmoking",
                    "non-smoking",
                    "bungalows",
                    "bungalow",
                    "suites",
                    "suite"
                ]
            },
            {
                "value": "OTHER",
                "synonyms": [
                    "speak to a manager",
                    "speak with the hotel",
                    "booking a room",
                    "contact the hotel",
                    "call the hotel",
                    "contact the property",
                    "electric car chargers",
                    "compass club room",
                    "pick up car",
                    "water park passes",
                    "smoke free property",
                    "contact hotel",
                    "water park",
                    "incidental deposit",
                    "upgraded room",
                    "room upgrade",
                    "wheel chair",
                    "smoking area",
                    "smoking property",
                    "property manager",
                    "luggage storage",
                    "beach equipment",
                    "rental car",
                    "car rental",
                    "phone number",
                    "free bar",
                    "turkish bath",
                    "ice bucket",
                    "smoke free",
                    "smoke-free property",
                    "smoke-free",
                    "currentbooking",
                    "contact",
                    "contacted",
                    "connect",
                    "property",
                    "booking",
                    "booked",
                    "wheelchair",
                    "reservations",
                    "reservation",
                    "concierge",
                    "booking",
                    "elevator",
                    "beverages",
                    "details",
                    "luggage",
                    "recontact",
                    "housekeeping",
                    "laundry",
                    "drinks",
                    "massage",
                    "floor",
                    "accessiblity",
                    "lobby",
                    "call",
                    "downstairs",
                    "package",
                    "contacting",
                    "calling",
                    "fees",
                    "fee",
                    "rental",
                    "alcohol",
                    "sofa",
                    "washer",
                    "eat",
                    "gym",
                    "register",
                    "call",
                    "book",
                    "sauna",
                    "tours",
                    "number",
                    "residence",
                    "email"
                ]
            }
        ],
        "valueSelectionStrategy": "TOP_RESOLUTION"
    },
    "FlightAmenities": {
        "enumerationValues": [
            {
                "value": "BAG",
                "synonyms": [
                    "carry on bag",
                    "carry on bags",
                    "back pack",
                    "back packs",
                    "carry on",
                    "carry ons",
                    "carry-on bag",
                    "carry-on bags",
                    "checked bag",
                    "checked bags",
                    "extra bag",
                    "extra bags",
                    "small bag",
                    "small bags",
                    "book bag",
                    "hand bag",
                    "personal item",
                    "personal items",
                    "handbag",
                    "carryon",
                    "carry-on",
                    "carry-ons",
                    "bookbag",
                    "lauggage",
                    "lagguge",
                    "lugage",
                    "luggagea",
                    "lagguage",
                    "loggage",
                    "luggage",
                    "lugagge",
                    "luggages",
                    "purse",
                    "suitcase",
                    "suitcases",
                    "thebagages",
                    "weight",
                    "bagage",
                    "bagages",
                    "bagged",
                    "baggage",
                    "bagagge",
                    "baggages",
                    "bags",
                    "bag"
                ]
            },
            {
                "value": "BOARDING_PASS",
                "synonyms": [
                    "boarding past",
                    "boarding pasd",
                    "boarding pass",
                    "boarding passes",
                    "board pass",
                    "board passes",
                    "tickets",
                    "ticket"
                ]
            },
            {
                "value": "CHECK_IN",
                "synonyms": [
                    "tsa pre check",
                    "check in",
                    "checkin in",
                    "checks in",
                    "check into",
                    "checked in",
                    "checked into",
                    "checking in",
                    "checking into",
                    "tsa pre-check",
                    "mobile pass",
                    "mobile passes",
                    "pre check",
                    "pre-check",
                    "booking",
                    "chekin",
                    "check",
                    "checkin",
                    "checking",
                    "checked",
                    "document",
                    "identification",
                    "passport",
                    "check-in"
                ]
            },
            {
                "value": "MEAL",
                "synonyms": [
                    "gluten free meal",
                    "gluten free meals",
                    "vegetarian meal",
                    "vegetarian meals",
                    "kosher meal",
                    "kosher meals",
                    "halal meal",
                    "halal meals",
                    "gluten-free meal",
                    "gluten-free meals",
                    "gluten free",
                    "meal option",
                    "meal options",
                    "keto friendly",
                    "keto-friendly",
                    "keto",
                    "vegetarian",
                    "kosher",
                    "halal",
                    "brekfast",
                    "breakfast",
                    "brekafast",
                    "lunch",
                    "dinner",
                    "food",
                    "meals",
                    "meal"
                ]
            },
            {
                "value": "PET_POLICY",
                "synonyms": [
                    "therapeutic chicken",
                    "service animal",
                    "service dog",
                    "animal companion",
                    "pets policy",
                    "pet policy",
                    "animal",
                    "animals",
                    "chicken",
                    "dog",
                    "doggy",
                    "pet",
                    "puppy",
                    "puppys",
                    "puppies",
                    "cat",
                    "cats",
                    "kitten",
                    "kittens",
                    "pets"
                ]
            },
            {
                "value": "SEAT",
                "synonyms": [
                    "emergency row",
                    "middle seat",
                    "isle seat",
                    "aisle seat",
                    "window seat",
                    "handicap seating",
                    "handicap seats",
                    "handicap seat",
                    "handicapped seating",
                    "handicapped seats",
                    "handicapped seat",
                    "window",
                    "middle",
                    "aisle",
                    "sat",
                    "seated",
                    "seaters",
                    "seating",
                    "seats",
                    "sit",
                    "sits",
                    "sitting",
                    "seat"
                ]
            },
            {
                "value": "WHEELCHAIR",
                "synonyms": [
                    "handicapped assistance",
                    "handicap assistance",
                    "handicap cart",
                    "wheel chair",
                    "wheel chairs",
                    "wheels chairs",
                    "wheelchair assistance",
                    "handicapped",
                    "assistance",
                    "wheelcharge",
                    "wheelchairs",
                    "wheelchair"
                ]
            },
            {
                "value": "OTHER",
                "synonyms": [
                    "baby basin",
                    "walking cane",
                    "airport transfers",
                    "airport transfer",
                    "lounge pass",
                    "check out",
                    "car rental",
                    "car seat",
                    "pick up",
                    "checked out",
                    "check flights",
                    "flight cost",
                    "child ticket",
                    "emergency exit",
                    "service representative",
                    "protocol",
                    "kg",
                    "transfers",
                    "transport",
                    "transportation",
                    "shuttle",
                    "internet",
                    "bassinet",
                    "documents",
                    "book",
                    "layover",
                    "airline",
                    "checkout",
                    "board",
                    "passport",
                    "passports",
                    "boarding",
                    "airport",
                    "car",
                    "airfare",
                    "kilos",
                    "billing",
                    "pnr",
                    "voucher",
                    "ID",
                    "number",
                    "departure",
                    "arrival",
                    "visa",
                    "wifi",
                    "reservation",
                    "reservations",
                    "pickup",
                    "pounds",
                    "id",
                    "online",
                    "contact",
                    "park",
                    "email",
                    "paper",
                    "times",
                    "economy"
                ]
            }
        ],
        "valueSelectionStrategy": "TOP_RESOLUTION"
    }
}
