
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-17T15:23:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d894646581e6630740ea1083e25c196686ecb660",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
