[tool.poetry]
name = "aiosqlembic"
version = "0.1.0"
description = "Migrations powered by aiosql"
authors = ["euri10 <benoit.barthelet@gmail.com>"]
license = "Unlicense"
readme = "README.rst"
repository = "https://gitlab.com/euri10/aiosqlembic"
documentation = "https://aiosqlembic.readthedocs.io/en/latest/"
keywords = ["asyncpg", "postgresql", "migration"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: Public Domain",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: SQL",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet :: WWW/HTTP",
    "Typing :: Typed"
]



[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.0.8"
pydantic = "^1.3"
alembic = "^1.3.2"
toml = "^0.10.0"
asyncpg = "^0.20.1"
jinja2 = "^2.11.0"
migra = "^1.0.1575954682"
aiosql = "^3.0.0"

[tool.poetry.scripts]
aiosqlembic = 'aiosqlembic.main:app'

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.11.1"
nest-asyncio = "^1.2.2"
pre-commit = "^1.21.0"
flake8 = "^3.7.9"
black = "19.10b0"
mypy = "0.761"
pytest-asyncio = "^0.10.0"
yappi = "^1.2.3"
pytest-cov = "^2.8.1"
coverage = "^5.0.3"
Sphinx = "^2.3.1"
sphinx-fontawesome = "^0.0.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
