language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install codecov python-coveralls pytest pytest-cov

script:
  - pytest --cov=./
after_success:
  - codecov    
  - coveralls
