[build-system]
requires = ["setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38
isolated_build = True

[testenv]
deps =
     pytest
     pytest-cov
commands =
    pytest --tb=short --doctest-modules --cov=llyfrau --cov-report term {posargs}

[testenv:pkg]
deps =
    wheel
commands =
    python setup.py sdist bdist_wheel
"""