[tool.poetry]
name = "pixler"
version = "0.1.2"
description = "Draw a pixel map with braille characters"
authors = ["Axel <pixler@absalon.is>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ikornaselur/pixler"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
ipython = "^7.12.0"
pdbpp = "^0.10.2"
ipdb = "^0.12.3"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.761"
flake8 = "^3.7.9"
flake8-builtins = "^1.4.2"
flake8-isort = "^2.8.0"
flake8-bugbear = "^20.1.4"
flake8-black = "^0.1.1"
flake8-comprehensions = "^3.2.2"
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
