[tool.poetry]
name = "ratus"
version = "0.0.1"
description = "Simple expression language."
authors = ["Nick Spain <nicholas.spain96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.8"
black = "19.10b0"
isort = "4.3.21"
sphinx = "^2.3"
pre-commit = "^2.0"
mypy = "^0.761.0"

setuptools = {version = "^45.1", optional = true}
wheel = {version = "^0.34.2", optional = true}
twine = {version = "^3.1", optional = true}

[tool.poetry.extras]
packaging = ["setuptools", "wheel", "twine"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
