# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision/enableVision.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from harix.rdk.proto.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vision/enableVision.proto',
  package='skill.vision',
  syntax='proto3',
  serialized_options=_b('\n!com.cloudminds.harix.skill.visionB\021EnableVisionProtoP\001'),
  serialized_pb=_b('\n\x19vision/enableVision.proto\x12\x0cskill.vision\x1a\x13\x63ommon/common.proto\"\xda\x01\n\rEnableRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x35\n\x08sub_type\x18\x02 \x01(\x0e\x32#.skill.vision.EnableRequest.SubType\x12\x0e\n\x06\x65nable\x18\x03 \x01(\x08\x12\x10\n\x08sub_addr\x18\x04 \x01(\t\x12\x12\n\nfaceset_id\x18\x05 \x01(\t\",\n\x07SubType\x12\r\n\tRECEPTION\x10\x00\x12\x08\n\x04\x46\x41LL\x10\x01\x12\x08\n\x04NAVI\x10\x02\"P\n\x0e\x45nableResponse\x12.\n\x0f\x63ommon_rsp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x32U\n\x0c\x45nableVision\x12\x45\n\x06\x65nable\x12\x1b.skill.vision.EnableRequest\x1a\x1c.skill.vision.EnableResponse\"\x00\x42\x38\n!com.cloudminds.harix.skill.visionB\x11\x45nableVisionProtoP\x01\x62\x06proto3')
  ,
  dependencies=[common_dot_common__pb2.DESCRIPTOR,])



_ENABLEREQUEST_SUBTYPE = _descriptor.EnumDescriptor(
  name='SubType',
  full_name='skill.vision.EnableRequest.SubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECEPTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAVI', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_ENABLEREQUEST_SUBTYPE)


_ENABLEREQUEST = _descriptor.Descriptor(
  name='EnableRequest',
  full_name='skill.vision.EnableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='skill.vision.EnableRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='skill.vision.EnableRequest.sub_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable', full_name='skill.vision.EnableRequest.enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_addr', full_name='skill.vision.EnableRequest.sub_addr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faceset_id', full_name='skill.vision.EnableRequest.faceset_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENABLEREQUEST_SUBTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=283,
)


_ENABLERESPONSE = _descriptor.Descriptor(
  name='EnableResponse',
  full_name='skill.vision.EnableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_rsp_info', full_name='skill.vision.EnableResponse.common_rsp_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable', full_name='skill.vision.EnableResponse.enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=365,
)

_ENABLEREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_ENABLEREQUEST.fields_by_name['sub_type'].enum_type = _ENABLEREQUEST_SUBTYPE
_ENABLEREQUEST_SUBTYPE.containing_type = _ENABLEREQUEST
_ENABLERESPONSE.fields_by_name['common_rsp_info'].message_type = common_dot_common__pb2._COMMONRSPINFO
DESCRIPTOR.message_types_by_name['EnableRequest'] = _ENABLEREQUEST
DESCRIPTOR.message_types_by_name['EnableResponse'] = _ENABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnableRequest = _reflection.GeneratedProtocolMessageType('EnableRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENABLEREQUEST,
  '__module__' : 'vision.enableVision_pb2'
  # @@protoc_insertion_point(class_scope:skill.vision.EnableRequest)
  })
_sym_db.RegisterMessage(EnableRequest)

EnableResponse = _reflection.GeneratedProtocolMessageType('EnableResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENABLERESPONSE,
  '__module__' : 'vision.enableVision_pb2'
  # @@protoc_insertion_point(class_scope:skill.vision.EnableResponse)
  })
_sym_db.RegisterMessage(EnableResponse)


DESCRIPTOR._options = None

_ENABLEVISION = _descriptor.ServiceDescriptor(
  name='EnableVision',
  full_name='skill.vision.EnableVision',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=367,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='enable',
    full_name='skill.vision.EnableVision.enable',
    index=0,
    containing_service=None,
    input_type=_ENABLEREQUEST,
    output_type=_ENABLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENABLEVISION)

DESCRIPTOR.services_by_name['EnableVision'] = _ENABLEVISION

# @@protoc_insertion_point(module_scope)
