[tool.poetry]
name = "seos"
version = "0.3.0"
description = "Simple Extractor on Sheets or SEOS wraps extraction on Google Sheets"
repository = "https://github.com/mamerisawesome/seos"
keywords = [
    "gsheets",
    "google-sheets",
    "sheets-scraping",
    "python-scraping",
    "data"
]
readme = "README.md"
authors = ["Almer Mendoza <atmalmer23@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"
google-api-python-client = "^1.7"
rainbow-bridge-logger = "^0.6.0"
oauth2client = "^3" # version 4 will not work for GSheets
google_auth_oauthlib = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "4.3"
coverage-badge = "^1.0.1"
coverage = "^5.0.3"
flake8 = "^3.7.9"
hypothesis = "^5.5.4"

[tool.poetry.scripts]
seos = "seos:extract_logs"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
