[tool.poetry]
name = "CloudMage"
version = "0.0.1"
description = "Cloud Simplifaction and Automation Magic."
license = "GPL-3.0-or-later"
authors = ["Rich Nason <rnason@cloudmage.io>"]
readme = "README.md"
include = [
    "CHANGELOG.md"
]
homepage = "https://github.com/TheCloudMage/PyPkgs-JinjaUtils"
packages = [
    {include = "cloudmage"}
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
coverage = "^5.0.3"
pylint = "^2.4.4"

[tool.poetry.scripts]
CloudMage = 'cloudmage.CloudMage'

[tool.poetry.urls]
"Releases" = "https://github.com/TheCloudMage/Common-Images/releases"
"Bug Tracking" = "https://github.com/TheCloudMage/Common-Images/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
