
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-12T23:42:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f76c00fd7e443a21c85d29bf187d371dde7f2fd",
 "version": "1.0.0.post.dev112"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
