cache:
  paths:
    - .pip
    - .tox

before_script:
  - pip --cache-dir=.pip install tox

py27:
  image: python:2.7
  script:
    - tox -e py27
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

py35:
  image: python:3.5
  script:
    - tox -e py35
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

py36:
  image: python:3.6
  script:
    - tox -e py36
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'
