parameters:
  loggerbundle:
    messageFormat': '%(asctime)s %(levelname)s - %(message)s'
    dateFormat': '%H:%M:%S'
    defaultLogLevel: 20 # INFO

services:
  loggerbundle.stdout.StreamHandlerFactory:
    arguments:
      - '%loggerbundle.messageFormat%'
      - '%loggerbundle.dateFormat%'

  loggerbundle.stdout.logHandler:
    class: logging.StreamHandler
    factory: ['@loggerbundle.stdout.StreamHandlerFactory', 'create']

  loggerbundle.azure.AzureLogHandlerFactory:
    arguments:
      - '%loggerbundle.azure.instrumentationKey%'

  loggerbundle.azure.AzureLogWithExtraHandler:
    factory: ['@loggerbundle.azure.AzureLogHandlerFactory', 'create']
