# Generated by Django 2.1 on 2019-12-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_press.BaseInquiry', verbose_name='問い合わせ系'),
        ),
    ]
