[tool.poetry]
name = "test-pypi-poetry"
version = "0.2.1"
description = "Testing PyPi & Poetry"
authors = ["Christopher Farrenden <cfarrend@gmail.com>"]

readme = "README_PUBLIC.md"
license = "Proprietary"

packages = [
    { include = "test-pypi-poetry" },
]

include = ["LOGO.png"]
exclude = ["test-pypi-poetry/README.md"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
