language: python
python:
- 2.7
sudo: false
services:
- redis
cache:
  directories:
  - eggs
install:
- python bootstrap.py -c ${BUILDOUT}
- bin/buildout -N -t 3 -c ${BUILDOUT} annotate
- bin/buildout -N -t 3 -c ${BUILDOUT}
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/test
env:
  matrix:
  - BUILDOUT=test-4.x.cfg
  - BUILDOUT=test-5.x.cfg
  - BUILDOUT=test-redis-4.x.cfg
  - BUILDOUT=test-redis-5.x.cfg
