resource_registry:
  OS::TripleO::Services::SkydiveAnalyzer: ../../deployment/skydive/skydive-analyzer-baremetal-ansible.yaml
  OS::TripleO::Services::SkydiveAgent: ../../deployment/skydive/skydive-agent-baremetal-ansible.yaml

#parameter_defaults:
#  SkydiveVars:
#    globals:
#      skydive_listen_ip: 0.0.0.0
#    analyzers:
#      skydive_analyzer_docker_command: "analyzer"
#    agents:
#      skydive_analyzer_docker_command: "agent"
