from .risk_factors_admin import RiskFactorsAdmin
from .anthropometry_admin import AnthropometryAdmin
from .diabetes_initial_review_admin import DiabetesInitialReviewAdmin
from .general_assessment_admin import GeneralAssessmentAdmin
from .general_assessment_initial_admin import GeneralAssessmentInitialAdmin
from .hiv_initial_review_admin import HivInitialReviewAdmin
from .hypertension_initial_review_admin import HypertensionInitialReviewAdmin
from .physical_activity_admin import PhysicalActivityAdmin
