[tool.poetry]
name = "past-mtl-monitors"
version = "0.1.0"
description = "A library for creating past metric temporal logic monitors."
repository = "https://github.com/mvcisback/past-mtl-monitors"
readme="README.md"
authors = ["Marcell Vazquez-Chanlatte <mvc@linux.com>"]

[tool.poetry.dependencies]
python = "^3.8"
attrs = "^19.3.0"
intervaltree = "^3.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
hypothesis = "^5.5.1"
codecov = "^2.0.15"
pytest-flake8 = "^1.0.4"
pytest-cov = "^2.8.1"
sphinx = "^2.4.2"
sphinx-autodoc-typehints = "^1.10.3"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
