[tool.poetry]
name = "mincli"
version = "0.1.0"
description = "A minimalistic CLI wrapper out to be the best"
authors = ["pascal <pascal@vks.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
argparse = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
