{{- if eq .Values.workloadType "stateful_set" }}
{{- $root := . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
      app.instance: {{ .Release.Name }}
  serviceName: {{ include "app.fullname" . }}-headless
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        app.instance: {{ .Release.Name }}
        {{- if .Values.image.tag }}
        app.image.version: {{ .Values.image.tag | quote }}
        {{- end }}
      annotations:
    {{- if .Values.istioInject }}
        sidecar.istio.io/inject: "true"
    {{- else }}
        sidecar.istio.io/inject: "false"
    {{- end }}
    {{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}{{ if .Values.image.tag }}{{ printf ":%s" .Values.image.tag }}{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PRO_ENV
            value: {{ .Values.global.gitbranch }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 10 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /PersistentLogs
            name: host-logs
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 10 -}}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 -}}
          {{- end }}
      {{- if .Values.usingCmpAgent }}
      initContainers:
      - env:
        - name: PRO_NAME
          value: {{ .Values.global.projectname }}
        - name: PRO_ENV
          value: {{ .Values.global.gitbranch }}
        image: "{{ .Values.global.init.image.repository }}:{{ .Values.global.init.image.tag }}"
        imagePullPolicy: {{ .Values.global.init.image.pullPolicy }}
        name: cmp-agent
        volumeMounts:
        - mountPath: /CMP_CONFIG
          name: config
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: host-logs
        hostPath:
          path: /data/_logs
    {{- with .Values.volumes }}
        {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- range .Values.persistence }}
      - persistentVolumeClaim:
          claimName: {{ include "app.fullname" $root }}-{{ .name }}
        name: {{ .name }}
    {{- end }}
{{- end }}
