[tool.poetry]
name = "CloudMage-JinjaUtils"
version = "1.0.0"
description = "Quickly and easily define, load, render and write Jinja templates."
license = "GPL-3.0-or-later"
authors = ["Rich Nason <rnason@cloudmage.io>"]
readme = "README.md"
include = [
    "CHANGELOG.md"
]
homepage = "https://github.com/TheCloudMage/PyPkgs-JinjaUtils"
packages = [
    {include = "jinjautils"}
]

[tool.poetry.dependencies]
python = "^3.6"
jinja2 = "^2.11.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
coverage = "^5.0.3"
pylint = "^2.4.4"

[tool.poetry.scripts]
JinjaUtils = 'jinjautils.jinja'

[tool.poetry.urls]
"Releases" = "https://github.com/TheCloudMage/PyPkgs-JinjaUtils/releases"
"Bug Tracking" = "https://github.com/TheCloudMage/PyPkgs-JinjaUtils/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
