# Generated by Django 3.0.3 on 2020-02-05 07:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('lessons', '0006_auto_20200205_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='lessons.Lesson')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_lessontag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lessons.LessonTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
