# Generated by Django 3.0.3 on 2020-02-11 19:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lessontagindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='script',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
