
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-15T19:22:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b7caeb58a6c2322a526166709210d67239def82",
 "version": "v2.0.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
