
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-20T17:40:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6922ce26d67c3ffe25d5136ed5901161cfc9366c",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
