[tool.poetry]
name = "aioeafm"
version = "0.1.2"
description = "An asyncio wrapper for the UK Environment Agency Flood Monitoring API"
authors = ["John Carr <john.carr@unrouted.co.uk>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.7.9"
pytest = "^5.3.5"
mypy = "^0.761"
pytest-aiohttp = "^0.3.0"
pylint = "^2.4.4"
coverage = "^5.0.3"
codecov = "^2.0.15"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
