[migrations]
base_directory = "/home/lotso/PycharmProjects/aiosqlembic/aiosqlembic/aiosqlembic_migrations"

[dsn]
scheme = "postgresql"
user = "postgres"
password = "postgres"
host = "localhost"
port = "5438"
db = "postgres"
