
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-20T16:45:34-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dff59ab3240b2d1f61a48a986e162838141cec97",
 "version": "v0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
