[tool.poetry]
name = "tohe"
version = "0.2.1"
description = "tohe - The friendly TODO list helper"
authors = ["Lukas Deutz <lukas.deutz@mailfence.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.5"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.4.4"
autopep8 = "^1.4.4"
pytest-cov = "^2.8.1"
pytest-mypy = "^0.4.2"

[tool.poetry.scripts]
tohe = "tohe.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

