from distutils.core import setup
setup(
  name = 'outlier_aniket',
  packages = ['outlier_aniket'],
  version = '0.7',
  license='MIT',
  description = 'Outlier Removal using Z-score or IQR',
  author = 'Aniket Gupta',
  author_email = 'aniketgupta1495@gmail.com',
  long_description_content_type="text/markdown",
  url = 'https://github.com/aniket1402/outlier_aniket.git',
  download_url = 'https://github.com/aniket1402/outlier_aniket/archive/v_07.tar.gz',
  keywords = ['Outlier Removal', 'Row Removal'],
  install_requires=[
          'numpy',
          'pandas',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
  ],
)