[tool.poetry]
name = "chatserver"
version = "0.1.0"
description = ""
authors = ["Luke Spademan <info@lukespademan.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^19.10b0", allow-prereleases = true}
pylint = "^2.4.4"

[tool.poetry.scripts]
run = "chatserver:chatserver.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
