- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - integrated-gate-storage
      - release-notes-jobs-python3
    check:
      jobs:
        - cinder-tempest-dsvm-lvm-lio-barbican
        - cinder-tox-bandit-baseline:
            voting: false
        - openstack-tox-functional-py36:
            irrelevant-files: &functional-irrelevant-files
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^cinder/locale/.*$
              - ^cinder/tests/hacking/.*$
              - ^cinder/tests/unit.*$
              - ^contrib/block-box.*$
              - ^doc/.*$
              - ^releasenotes/.*$
        - openstack-tox-functional-py37:
            irrelevant-files: *functional-irrelevant-files
        - cinder-rally-task:
            voting: false
        - openstack-tox-pylint:
            voting: false
            timeout: 5400
            irrelevant-files: *functional-irrelevant-files
        - cinder-plugin-ceph-tempest:
            voting: false
            irrelevant-files: &gate-irrelevant-files
              - ^(test-|)requirements.txt$
              - ^lower-constraints.txt$
              - ^.*\.rst$
              - ^api-ref/.*$
              - ^cinder/cmd/status\.py$
              - ^cinder/locale/.*$
              - ^cinder/tests/functional.*$
              - ^cinder/tests/hacking/.*$
              - ^cinder/tests/unit.*$
              - ^contrib/block-box.*$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$
        - cinder-grenade-dsvm-mn-sub-volbak:
            irrelevant-files: *gate-irrelevant-files
        - legacy-tempest-dsvm-lvm-multibackend:
            voting: false
            irrelevant-files: *gate-irrelevant-files
        - legacy-tempest-dsvm-full-devstack-plugin-nfs:
            voting: false
            irrelevant-files: *gate-irrelevant-files
        - tempest-slow-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-integrated-storage:
            irrelevant-files: *gate-irrelevant-files
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *gate-irrelevant-files
    gate:
      jobs:
        - cinder-grenade-dsvm-mn-sub-volbak:
            irrelevant-files: *gate-irrelevant-files
        - tempest-integrated-storage:
            irrelevant-files: *gate-irrelevant-files
        - grenade-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *gate-irrelevant-files
    experimental:
      jobs:
        - tempest-cinder-v2-api:
            irrelevant-files: *gate-irrelevant-files
        - legacy-tempest-dsvm-zeromq-multibackend:
            irrelevant-files: *gate-irrelevant-files
        - legacy-tempest-dsvm-multibackend-matrix:
            irrelevant-files: *gate-irrelevant-files
        - cinder-grenade-dsvm-mn-sub-volschbak:
            irrelevant-files: *gate-irrelevant-files
        - cinder-grenade-dsvm-mn-sub-bak:
            irrelevant-files: *gate-irrelevant-files
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files: *gate-irrelevant-files
        - tempest-pg-full:
            irrelevant-files: *gate-irrelevant-files
        - tempest-full-py3-opensuse15:
            irrelevant-files: *gate-irrelevant-files

- job:
    # Previously named legacy-tempest-dsvm-full-lio
    name: cinder-tempest-dsvm-lvm-lio-barbican
    parent: legacy-dsvm-base
    run: playbooks/legacy/cinder-tempest-dsvm-lvm-lio-barbican/run.yaml
    post-run: playbooks/legacy/cinder-tempest-dsvm-lvm-lio-barbican/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/barbican
      - openstack/cinderlib
      - openstack/python-barbicanclient
      - openstack/tempest
      - openstack/os-brick
    irrelevant-files: *gate-irrelevant-files

- job:
    # Security testing for known issues
    name: cinder-tox-bandit-baseline
    parent: openstack-tox
    timeout: 2400
    vars:
      tox_envlist: bandit-baseline
    required-projects:
      - openstack/requirements
    irrelevant-files: *gate-irrelevant-files

- job:
    name: cinder-rally-task
    parent: rally-task-cinder
    timeout: 7800
    vars:
      devstack_localrc:
        OSPROFILER_COLLECTOR: redis
      devstack_plugins:
        osprofiler: https://opendev.org/openstack/osprofiler
        rally-openstack: https://opendev.org/openstack/rally-openstack
      rally_task: rally-jobs/cinder.yaml
    required-projects:
      - openstack/rally-openstack
      - openstack/osprofiler

- job:
    name: cinder-plugin-ceph-tempest
    parent: devstack-plugin-ceph-tempest
    run: playbooks/tempest-and-cinderlib-run.yaml
    required-projects:
      - openstack/cinderlib
      - openstack/tempest

- job:
    name: cinder-grenade-dsvm-mn-sub-bak
    parent: legacy-dsvm-base-multinode
    # Old name: legacy-grenade-dsvm-cinder-mn-sub-bak
    # This is py3 version for ussuri onwards rest all branch needs to be py2
    # version which is present in openstack-zuul-jobs.
    # We need to take care of this branch variant and python version while
    # migrating these jobs to zuulv3.
    branches: ^(?!(driverfixes|stable/(ocata|pike|queens|rocky|stein|train))).*$
    run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-bak/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-bak/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/cinder

- job:
    name: cinder-grenade-dsvm-mn-sub-volbak
    parent: legacy-dsvm-base-multinode
    # Old name: legacy-grenade-dsvm-cinder-mn-sub-volbak
    # This is py3 version for ussuri onwards rest all branch needs to be py2
    # version which is present in openstack-zuul-jobs.
    # We need to take care of this branch variant and python version while
    # migrating these jobs to zuulv3.
    branches: ^(?!(driverfixes|stable/(ocata|pike|queens|rocky|stein|train))).*$
    run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-volbak/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-volbak/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/cinder

- job:
    name: cinder-grenade-dsvm-mn-sub-volschbak
    parent: legacy-dsvm-base-multinode
    # Old name: legacy-grenade-dsvm-cinder-mn-sub-volschbak
    # This is py3 version for ussuri onwards rest all branch needs to be py2
    # version which is present in openstack-zuul-jobs.
    # We need to take care of this branch variant and python version while
    # migrating these jobs to zuulv3.
    branches: ^(?!(driverfixes|stable/(ocata|pike|queens|rocky|stein|train))).*$
    run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-volschbak/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-cinder-mn-sub-volschbak/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/cinder
