site_name: nersights
site_description: Debug annotated Named Entity Recognition (NER) data for inconsitencies and get insights on improving the quality of your data.
site_url: https://kabirkhan.github.com/nersights

theme:
    name: 'material'
    palette:
        primary: 'orange'
        accent: 'deep-orange'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: 'kabirkhan/nersights'
repo_url: 'https://github.com/kabirkhan/nersights'
edit_uri: 'https://github.com/kabirkhan/nersights'

nav:
    - Introduction: 'index.md'
    - Features: 'features.md'
    - API:
        - Dataset: 'api/dataset.md'
        - Insights: 'api/insights.md'
        - Stats: 'api/stats.md'
        - Validation: 'api/validation.md'
    - Development - Contributing: 'contributing.md'
    - Release Notes: release-notes.md

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite
    - extra
    - mkautodoc


extra:
    social:
        - type: 'github'
          link: 'https://github.com/kabirkhan/nersights'
        - type: 'twitter'
          link: 'https://twitter.com/kabir_khan14'

extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'js/termynal.js'
    - 'js/custom.js'
