
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-18T15:37:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f575948f4d41efd3499d76e1677545134a65b10",
 "version": "2020.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
