[tool.poetry]
name = "test-pypi-poetry"
version = "0.2.2"
description = "Testing PyPi & Poetry"
license = "Proprietary"
authors = ["Christopher Farrenden <cfarrend@gmail.com>"]

readme = "README_PUBLIC.md"
homepage = "https://cfarrend.com"
repository = "https://github.com/cfarrend/test-pypi-poetry"
documentation = "https://github.com/cfarrend/test-pypi-poetry/blob/master/README.md"

packages = [
    { include = "test-pypi-poetry" },
]

include = ["LOGO.png"]
exclude = ["test-pypi-poetry/README.md"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/cfarrend/test-pypi-poetry"
"License" = "https://github.com/cfarrend/test-pypi-poetry/blob/master/LICENSE"
"Official Website" = "https://google.com.au/"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
