[tool.black]
target-version = "py27"
skip-string-normalization = true

[tool.poetry]
name = "pyberny"
version = "0.5.0"
description = "Molecular/crystal structure optimizer"
readme = "README.md"
authors = ["Jan Hermann <dev@jan.hermann.name>"]
repository = "https://github.com/jhrmnn/pyberny"
documentation = "https://jhrmnn.github.io/pyberny"
license = "MPL-2.0"
packages = [
    { include = "berny" },
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
numpy = "^1.15"
pytest = { version = "^3.6", optional = true }
sphinx = { version = "^1.7", optional = true }
coverage = { version = "^4.5", optional = true }
toml = { version = "^0.10.0", optional = true }

[tool.poetry.extras]
test = ["pytest"]
cov = ["coverage"]
doc = ["sphinx", "toml"]

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = { version = "^18.8", python = "^3.5" }
flake8-comprehensions = "^1.4"
flake8-quotes = "^1.0"
isort = "^4.3"
pydocstyle = "^3.0"
black = { version = "^19-beta.0", allow-prereleases = true, python = "^3.6" }

[tool.poetry.scripts]
berny = "berny.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
