arangodb:
  DB_end_point: createDB
  DB_service_host: arangoml.arangodb.cloud
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: https
  dbName: MLeygnbvyhy26qnocwubwp7p
  password: MLehanla2cya7lyv9gduiyq
  username: ML75os8zggx0fntz9k9had2
mlgraph:
  graphname: enterprise_ml_graph
