[build-system]
requires = ["setuptools", "setuptools_scm", "wheel"]
build-backend = 'setuptools.build_meta'

[tool.towncrier]
    package = "parfive"
    package_dir = "."
    directory = "changelog"
    filename = "CHANGELOG.rst"
    issue_format = "`#{issue} <https://github.com/Cadair/parfive/pull/{issue}>`__"
