[tool.poetry]
name = "smarty_py"
version = "0.1.3"
description = "A CLI for SmartRecruiters solutions consulting."
authors = ["Elliott Maguire <e.maguire@smartrecruiters.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.22.0"
colorama = "^0.4.3"
names = "^0.3.0"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"
black = "19.3b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
