[tool.poetry]
name = "where-to"
version = "0.2-alpha.1"
description = "Show upcoming Outlook meetings on the Windows lock screen"
authors = ["Blair Conrad <blair@blairconrad.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/blairconrad/where-to.git"


[tool.poetry.scripts]
where-to = "where_to.cli:main"

[tool.poetry.plugins."gui_scripts"]
where-to-no-console = "where_to.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
pywin32 = "^227"
PILLOW = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
