- project:
    templates:
      - openstack-python35-jobs
      - openstack-python-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
      - openstackclient-plugin-jobs
    check:
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
        - openstack-tox-lower-constraints
        - openstack-tox-cover
    gate:
      queue: ironic
      jobs:
        - ironicclient-dsvm-functional
        - ironicclient-tempest-dsvm-src
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
