
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d9825f18dc6a70b5b4ef6bc5bf48d8025eef1e8e",
 "version": "0.18.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
