[tool.poetry]
name = "magit"
version = "0.1.0"
description = "Multi repo Git manager"
authors = ["Pavel Brodsky <pavel.brodsky@forter.com>"]
packages = [
    { include = "mag" }
]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
