[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "anthonnn"
author = "Rizaldi Martaputra"
author-email = "rizaldi.m@bridestory.com"
classifiers = ["License :: OSI Approved :: MIT License"]

