[tool.poetry]
name = "clitt"
version = "1.2.1"
description = "Use Twitter from your terminal!"
authors = ["Joao Vitor Maia <maia.tostring@gmail.com>"]
repository = "https://github.com/leviosar/clitt"
documentation = "https://github.com/leviosar/clitt"
readme = "README.md"

keywords = ["Twitter", "Client", "Command-line"]

[tool.poetry.dependencies]
python = "^3.7"
tweepy = "^3.8"
colorama = "^0.4.1"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
clitt = "clitt.__main__:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
