language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-extras
    - python: 2.7
      env: TOX_ENV=py27-noextras

    - python: pypy
      env: TOX_ENV=pypy-extras
    - python: pypy
      env: TOX_ENV=pypy-noextras

    - python: 3.5
      env: TOX_ENV=py35-extras
    - python: 3.5
      env: TOX_ENV=py35-noextras

    - python: 3.6
      env: TOX_ENV=py36-extras
    - python: 3.6
      env: TOX_ENV=py36-noextras

    - python: 3.7
      env: TOX_ENV=py37-extras
    - python: 3.7
      env: TOX_ENV=py37-noextras

    - python: 3.8
      env: TOX_ENV=py38-extras
    - python: 3.8
      env: TOX_ENV=py38-noextras

install:
    - sudo apt-get install graphviz
    - pip install tox coveralls

script:
    - tox -e $TOX_ENV

after_success:
    - tox -e coverage-report
    - coveralls
