
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-02-13T12:50:58-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1055d5d9cfde0cf59cdd1860b4c4fdb4fac4d4e5",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
