--- 
addons: 
  apt: 
    packages: 
      - libbz2-dev
      - libcurl4-openssl-dev
      - libssl-dev
compiler: 
  - gcc
  - clang
dist: xenial
language: python
matrix: 
  include: 
    - 
      os: linux
      python: 2.7
      install: 
        - pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      os: linux
      python: 3.5
      before_install:
        - sudo apt-get update && sudo apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev
      install: 
        - pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      os: linux
      python: 3.6.5
      before_install:
        - sudo apt-get update && sudo apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev
      install: 
        - pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      os: linux
      python: 3.7.3
      before_install:
        - sudo apt install build-essential
      install: 
        - pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      language: generic
      os: osx
      python: 2.7
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
      install: 
        - sudo pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      language: generic
      os: osx
      python: 3.5
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
      install: 
        - sudo pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      language: generic
      os: osx
      python: 3.6.5
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
      install: 
        - sudo pip install . -r requirements.txt
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
    - 
      language: generic
      os: osx
      python: 3.7.3
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
      install: 
        - sudo pip install . -r requirements.txt 
      script:
        - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500

os: linux
script: 
  - flake8 --config .flake8
  - pytest --cov=.
  - bam2fasta convert --filename ./bam2fasta/tests/test-data/10x-example/possorted_genome_bam.bam --min-umi-per-barcode 10 --barcodes-file ./bam2fasta/tests/test-data/10x-example/barcodes.tsv --rename-10x-barcodes ./bam2fasta/tests/test-data/10x-example/barcodes_renamer.tsv --processes 4 --line-count 1500
  - codecov
