
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-12T16:26:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9240f6009b5c9d2cbd47219fb05dd111e67b99e",
 "version": "0.77.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
