# Generated by Django 2.1 on 2019-12-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0002_auto_20191220_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='form',
            field=models.CharField(max_length=100),
        ),
    ]
