[tool.poetry]
name = "marmot"
version = "0.1.4"
description = "Ensemble modeling with hyperparameter tuner"
license = "MIT"
readme = "README.rst"
authors = ["horoiwa <horoiwa195@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.17"
pandas = "^0.25.3"
scikit-learn = "^0.21.3"
scipy = "^1.3"
optuna = "^0.18.1"
xgboost = "^0.90.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

