
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-20T20:59:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "038a7fa81991a921a2b95cc65a58162489ea5956",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
