- job:
    name: shade-tox-py27-tips
    parent: openstack-tox-py27
    description: |
      Run tox python 27 unittests against master of important libs
    vars:
      tox_install_siblings: true
      zuul_work_dir: src/opendev.org/openstack/shade
    # shade in required-projects so that os-client-config and keystoneauth
    # can add the job as well
    required-projects:
      - openstack/shade
      - openstack/keystoneauth
      - openstack/openstacksdk
      - openstack/os-client-config

- job:
    name: shade-tox-py35-tips
    parent: openstack-tox-py35
    description: |
      Run tox python 35 unittests against master of important libs
    vars:
      tox_install_siblings: true
      zuul_work_dir: src/opendev.org/openstack/shade
    # shade in required-projects so that os-client-config and keystoneauth
    # can add the job as well
    required-projects:
      - openstack/shade
      - openstack/keystoneauth
      - openstack/openstacksdk
      - openstack/os-client-config

- project-template:
    name: shade-tox-tips
    check:
      jobs:
        - shade-tox-py27-tips
        - shade-tox-py35-tips
    gate:
      jobs:
        - shade-tox-py27-tips
        - shade-tox-py35-tips

- job:
    name: shade-functional-devstack-base
    parent: devstack-tox-functional-consumer
    description: |
      Base job for shade devstack-based functional tests
    post-run: playbooks/devstack/post.yaml
    required-projects:
      # These jobs will DTRT when shade triggers them, but we want to make
      # sure stable branches of shade never get cloned by other people,
      # since stable branches of shade are, well, not actually things.
      - name: openstack/shade
        override-checkout: master
      - name: openstack/heat
      - name: openstack/swift
    timeout: 9000
    vars:
      devstack_local_conf:
        post-config:
          $CINDER_CONF:
            DEFAULT:
              osapi_max_limit: 6
      devstack_services:
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
      tox_environment:
        # Do we really need to set this? It's cargo culted
        PYTHONUNBUFFERED: 'true'
        # Is there a way we can query the localconf variable to get these
        # rather than setting them explicitly?
        SHADE_HAS_DESIGNATE: 0
        SHADE_HAS_HEAT: 1
        SHADE_HAS_MAGNUM: 0
        SHADE_HAS_NEUTRON: 1
        SHADE_HAS_SWIFT: 1
      tox_install_siblings: false
      tox_envlist: functional
      zuul_work_dir: src/opendev.org/openstack/shade

- job:
    name: shade-functional-devstack-legacy
    parent: shade-functional-devstack-base
    description: |
      Run shade functional tests against a legacy devstack
    # TODO(mordred): This does not seem to work
    voting: false
    vars:
      devstack_localrc:
        ENABLE_IDENTITY_V2: true
        FLAT_INTERFACE: br_flat
        PUBLIC_INTERFACE: br_pub
      tox_environment:
        SHADE_USE_KEYSTONE_V2: 1
        SHADE_HAS_NEUTRON: 0
    override-checkout: stable/newton

- job:
    name: shade-functional-devstack
    parent: shade-functional-devstack-base
    description: |
      Run shade functional tests against a master devstack
    vars:
      devstack_localrc:
        Q_SERVICE_PLUGIN_CLASSES: qos
        Q_ML2_PLUGIN_EXT_DRIVERS: qos,port_security

- job:
    name: shade-functional-devstack-python3
    parent: shade-functional-devstack
    description: |
      Run shade functional tests using python3 against a master devstack
    vars:
      shade_environment:
        SHADE_TOX_PYTHON: python3

- job:
    name: shade-functional-devstack-tips
    parent: shade-functional-devstack
    description: |
      Run shade functional tests with tips of library dependencies against a
      master devstack.
    required-projects:
      - name: openstack/keystoneauth
      - name: openstack/openstacksdk
      - name: openstack/os-client-config
    vars:
      tox_install_siblings: true

- job:
    name: shade-functional-devstack-tips-python3
    parent: shade-functional-devstack-tips
    description: |
      Run shade functional tests with tips of library dependencies using
      python3 against a master devstack.
    vars:
      tox_environment:
        SHADE_TOX_PYTHON: python3

- job:
    name: shade-functional-devstack-magnum
    parent: shade-functional-devstack
    description: |
      Run shade functional tests against a master devstack with magnum
    required-projects:
      - openstack/magnum
      - openstack/python-magnumclient
    vars:
      devstack_plugins:
        magnum: https://opendev.org/openstack/magnum
      devstack_localrc:
        MAGNUM_GUEST_IMAGE_URL: https://tarballs.openstack.org/magnum/images/fedora-atomic-f23-dib.qcow2
        MAGNUM_IMAGE_NAME: fedora-atomic-f23-dib
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      tox_environment:
        SHADE_HAS_SWIFT: 0
        SHADE_HAS_MAGNUM: 1
    voting: false

- job:
    name: shade-ansible-functional-devstack
    parent: shade-functional-devstack
    description: |
      Run shade ansible functional tests against a master devstack
      using released version of ansible.
    vars:
      tox_envlist: ansible

- job:
    name: shade-ansible-stable-2.5-functional-devstack
    parent: shade-ansible-functional-devstack
    description: |
      Run shade ansible functional tests against a master devstack
      using git devel branch version of ansible.
    branches: ^(devel|master)$
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.5
      - name: openstack/shade
        override-checkout: master
      - name: openstack/devstack
        override-checkout: master
    vars:
      # test-matrix grabs branch from the zuul branch setting. If the job
      # is triggered by ansible, that branch will be stable-2.5 which doesn't
      # make sense to devstack. Override so that we run the right thing.
      test_matrix_branch: master
      tox_install_siblings: true

- project-template:
    name: shade-functional-tips
    check:
      jobs:
        - shade-functional-devstack-tips
        - shade-functional-devstack-tips-python3
    gate:
      jobs:
        - shade-functional-devstack-tips
        - shade-functional-devstack-tips-python3

- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - publish-to-pypi
      - release-notes-jobs-python3
      - shade-functional-tips
      - shade-tox-tips
    check:
      jobs:
        - bifrost-integration-tinyipa:
            voting: false
        - bifrost-integration-tinyipa-opensuse-15:
            voting: false
        - shade-ansible-stable-2.5-functional-devstack:
            voting: false
        - shade-ansible-functional-devstack
        - shade-functional-devstack
        - shade-functional-devstack-magnum
        - shade-functional-devstack-python3
    gate:
      jobs:
        - shade-ansible-functional-devstack
        - shade-functional-devstack
        - shade-functional-devstack-python3
