
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-17T00:11:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "38dae4c539936582e986ed9efbefbd31ba134e04",
 "version": "0.16.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
